### ISSUE TITLE
Not Working in Eclipse

### ISSUE THREAD

**Issue by jeffrschneider** [extjwnl/extjwnl#18] opened 2017-02-02 01:42 UTC
I'm able to download and install the extjwnl perfectly from mvn command line but when I try to bring it into Eclipse, it fails. Has anyone else seen this? Fixes available?

**Comment by logological** [comment] 2017-02-02 11:08
Works fine for me.  How exactly are you using extjwnl with Eclipse, and what is the error message you're seeing?

**Comment by jeffrschneider** [comment] 2017-02-02 12:30
I've tried it on a couple machines with no luck. Here are some additional details: 
Eclipse IDE for Java Developers
Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

The error is in the first attempt to initiate the package... 
Dictionary dictionary = Dictionary.getDefaultResourceInstance();

Exception in thread "main" java.lang.IllegalArgumentException
	at net.sf.extjwnl.dictionary.Dictionary.getInstance(Dictionary.java:178)
	at net.sf.extjwnl.dictionary.Dictionary.getResourceInstance(Dictionary.java:294)
	at net.sf.extjwnl.dictionary.Dictionary.getDefaultResourceInstance(Dictionary.java:282)

Perhaps the project .pom wasn't packaged in a way that would work with this version of Eclipse?

A couple additional points:
1. The command line maven install of the project was successful; all unit tests succeeded. 
2. After lots of failures in Eclipse, I created a new Eclipse project that has nothing else in it (no other potential conflicts with classpath, etc.). The simplest "hello world" that leverages extjwnl fails in Eclipse.

**Comment by jeffrschneider** [comment] 2017-02-02 13:22
Okay - I think I got it. If you do the mvn install, it produces this:
    <groupId>net.sf.extjwnl</groupId>
    <artifactId>extjwnl-parent</artifactId>
    <packaging>pom</packaging>
    <version>**1.9.3-SNAPSHOT**</version>
    <name>extJWNL Parent</name>
    <description>extJWNL Parent</description>
    <url>http://extjwnl.sf.net</url>

==============
In Eclipse, I modified the .POM to state:
	<dependency>
	  <groupId>net.sf.extjwnl</groupId>
	  <artifactId>extjwnl-utilities</artifactId>
	  <version>1.9.2</version>
	</dependency>

And now it works... I'd keep this issue open.

**Comment by autayeu** [comment] 2017-02-02 19:34
Dictionary.getDefaultResourceInstance() might fail due to missing resources in classpath. I'd advise to take a look at your setup - most likely there is something to be improved there. -snapshot prefix is normal - you've checked out development branch, that's what it contains.

Jeff, I'd close this, and if there is something specific you'd like to be done in the project about this issue, reopen with a suggestion. Thank you!

**Closed by autayeu** 2017-02-02 19:34 UTC

**Comment by jeffrschneider** [comment] 2017-02-02 20:56
I'm confused. Did you test this in Eclipse and validate that there is no problem?

**Comment by autayeu** [comment] 2017-02-02 20:59
No, I don't use it. Given it works in CLI (and IDEA), I think it's something with Eclipse.

**Comment by jeffrschneider** [comment] 2017-02-02 21:22
To clarify - Eclipse works with version 1.9.2, and Eclipse does not work with 1.9.3-SNAPSHOT. Personally, I'm not comfortable claiming that "there's no open issues between Eclipse and extjwnl", as there seems to be. My recommendation is to keep the issue open so that other people know the problem continues to exist. Alternatively, you can test the two together and if the error isn't reproducible, you should close it. Obviously, your call.

**Comment by autayeu** [comment] 2017-02-02 21:26
Out of curiosity, I've downloaded Eclipse (the "Eclipse IDE for Java Developers"), imported extJWNL (master branch, 1.9.3-SNAPSHOT) as a Maven project (File-Import-etc) and run Examples.java (the green button :). It runs normally. So, maybe there is an issue (indeed you have one), but I'm not sure it has to do with the project - at least the issue is not reproducible by two other people (me and logological above). Maybe you can find someone with Eclipse expertise to figure that out with you.

**Comment by autayeu** [comment] 2017-02-02 21:29
Eclipse I used is this one:
Eclipse IDE for Java Developers

Version: Neon.2 Release (4.6.2)
Build id: 20161208-0600

It's newer than the one you're using. Maybe your issue can be fixed by an upgrade (if that's possible). Maybe someone more experienced can help you. And if there is something to be fixed in the project - let's fix it, a pull request would be nice.

**Comment by jeffrschneider** [comment] 2017-02-02 22:33
I appreciate you looking into it. I upgraded to Neon.2 4.6.2 last night as well and it didn't fix the problem. I wish I had a quick answer for you but I don't. I had a friend try it on his computer and he was seeing the same error as me. Let's let it go; if others run into it, they'll see the work around. Again - thank you for the work you've done on the project - and thank you for looking into the problem I encountered.

**Comment by autayeu** [comment] 2017-02-02 23:01
Jeff, maybe resetting some settings would do? Semi-random things I would try: create a new workspace\delete Eclipse settings folder in your user profile\check Maven installation\clear local Maven repository cache\importing clean project.

**Comment by pranayat** [comment] 2022-01-12 20:48
I was able to reproduce this issue in Eclipse. This happened because I had missed adding the 'extjwnl-data-wn31' dependency (I am not using Maven and had missed adding this dependency manually). Adding the 'extjwnl-data-wn31' fixed it.

**Comment by autayeu** [comment] 2022-01-13 21:50
@pranayat Thank you for sharing this and the solution!
